version: "3.8"
services:
  app:
    build: .
    ports:
      - "3010:3010"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5442/forms
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forms
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
